#cloud-config
fqdn: {{ CONTROLLER_HOSTNAME }}
hostname: {{ CONTROLLER_HOSTNAME }}
preserve_hostname: false
prefer_fqdn_over_hostname: true
write_files:
# start sso block #
- path: /etc/dex/sso.yaml
  content: |
    type: {{ IDP_TYPE }}
    id: {{ IDP_ID }}
    name: {{ IDP_NAME }}
    config:
      issuer: {{ IDP_ISSUER_URL }}
      clientID: {{ IDP_CLIENT_ID }}
      clientSecret: {{ IDP_CLIENT_SECRET }}
      redirectURI: $DEX_ORIGIN/dex/callback
# end sso block #
- path: /etc/bowtie-server.d/custom.conf
  content: |
    SITE_ID={{ SITE_ID }}
    BOWTIE_SYNC_PSK={{ SYNC_PSK }}
# start init-users block #
- path: /var/lib/bowtie/init-users
  content: |
    {{ INIT_USER_CREDENTIALS }}
# end init-users block #
# start should-join block #
- path: /var/lib/bowtie/should-join.conf
  content: |
    entrypoint = {{ FIRST_CONTROLLER_HOSTNAME }}
# end should-join block #
- path: /var/lib/bowtie/skip-gui-init
- path: /etc/update-at
# start ssh key block #
users:
- name: root
  ssh_authorized_keys:
  - {{ PUBLIC_SSH_KEY }}
  lock_passwd: true
# end ssh key block #
